### PR TITLE
Add Linsensuppe

### PR DESCRIPTION
**Pull request by neeklamy**
@schnittchen, you forgot to make a PR for this addition, I’ve done it for you.

Additionally, it’s always best to write commits using imperative mode (Add > Added), here’s the rationale explained in this helpful article, [How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/#imperative):

>Imperative mood just means "spoken or written as if giving a command or instruction". A few examples:

> - Clean your room
> - Close the door
> - Take out the trash

Thanks

### CODE REVIEW

**Comment by schnittchen** [comment]
Oh thanks. How did you even see this?

I'll resolve conflicts as soon as I find time.

**Comment by neeklamy** [comment]
Glad to help. I was just digging around in the [justdelete\.me network](/rmlewisuk/justdelete.me/network), seeing if there were any loose ends. There really should be an easier way to find this stuff out…

**Comment by schnittchen** [comment]
Looks like this has already been dealt with in https://github.com/rmlewisuk/justdelete.me/pull/522, also 2a5addf80fd8eb60549c65e4da3aea5e9573561b introduces the change.

**Comment by neeklamy** [comment]
Ah, my mistake, I was checking against the site [Just Delete Me](http://justdelete.me/) instead of the repo, and it wasn’t listed there.

**Pull request closed without merging**
